
import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#fff'
  },
  containerHeader:{
      justifyContent:'flex-start',
      padding:23,
      paddingTop:44
  },
  containerHeaderLogo:{
       width:27,
       height:23,
  },
  containerForm:{
    width:wp('98%'),
    height:176,
    marginTop:40,

    left:9,
  },
  containerForm1:{
    justifyContent:'center',
    alignItems:'center',
    width:wp('98%'),
  },
  containerFormLeft:{
    padding:23
  },
  containerFormLeftLogo:{
    width:60,
    height:20,
    marginBottom:10
  },
  containerFormLeftTitle:{
     fontSize:14,
     color:'#ffff',
  },
  containerbody:{
      justifyContent:'space-between',
      flexDirection:'row',
      alignItems:'center',
      paddingHorizontal:20
  },
  containerbodyText:{
      fontSize:30,
      color:'#000000',
      fontFamily:'muli-bold'
  },
  containerFormBottomCenter:{
    justifyContent:'center',
    alignItems:'center',
    marginTop:-5 ,
  },
  containerFormBottom:{
      width:280,
      height:40,
      backgroundColor:'#fff',
      borderRadius:46,

      justifyContent:'center',
      flexDirection:'row',
      alignItems:'center',
  },
  containerFormBottomText:{
    fontSize:14,
    color:'#191921',
    fontFamily:'muli-bold',
    marginHorizontal:5
  },
  containerFormBottomIcon:{
    width:27,
    height:24
  },
  containerPagaments:{
  marginTop:30,
  },
  containerPagamentsText:{
    fontSize:14,
    color:'#191921',
    fontFamily:'muli-regular',
    marginHorizontal:5,
    padding:13,
  },
  containerPagamentsForm:{
    backgroundColor:'#E6E6E6',
    width:wp('94%'),
    height:90,
    borderRadius:21,
    marginTop:20
  },

  containerPagamentsFormLeft:{
       padding:23,
       flexDirection:'row',
       alignItems:'center'
  },
  containerPagamentsFormLeftIcon:{
        width:30,
        height:20,
        backgroundColor:'#B3B3B3',
        borderRadius:18
  },
  containerPagamentsFormLeftText:{
    fontSize:13,
    color:'#666666',
    fontFamily:'muli-bold',
    marginHorizontal:5
  },
  containerPagamentsFormBottomContainer:{
        marginTop:-33
  },
  containerPagamentsFormBottomContainerBottom:{
    padding:23,
    flexDirection:'row',
    alignItems:'center',
  },
  containerPagamentsFormBottomContainerBottomIcon:{
        width:20,
        height:20,
        marginHorizontal:5
  },
  containerPagamentsFormBottomContainerBottomText:{
    fontSize:13,
    color:'#0071BC',
    fontFamily:'Roboto-Bold',
    marginHorizontal:5
  },
  containerHistory:{
    padding:23,
  },
  containerHistoryTitle:{
    fontSize:20,
    color:'#000',
    fontFamily:'muli-bold',
    marginHorizontal:5
  }

});

export default styles;
